import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { checkout } from '../checkout'

export default function Home() {

  function formatAmountForStripe(amount, currency) {
    let numberFormat = new Intl.NumberFormat(['en-US'], {
      style: 'currency',
      currency: currency,
      currencyDisplay: 'symbol',
    })
    const parts = numberFormat.formatToParts(amount)
    let zeroDecimalCurrency = true;
    for (let part of parts) {
      if (part.type === 'decimal') {
        zeroDecimalCurrency = false
      }
    }
    return zeroDecimalCurrency ? amount : Math.round(amount * 100)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Canvas - Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Canvas Subscription models
        </h1>

        <div className={styles.grid}>

          <div className={styles.card}>
            <Image src="/images/IMG_4860.png" alt="NFT" width={200} height={200} />
            <p>Starter</p>
            <button onClick={(() => {
                checkout({
                  lineItems: [
                    {
                      price: "price_1LKJFNSJFDFywDTJsJeN1jw1",
                      quantity: 1,
                      amount: formatAmountForStripe(1000, CURRENCY),
                      currency: CURRENCY,
                    }
                  ]
                })
              })}>Buy @ $7
            </button>
          </div>
            
          <div className={styles.card}>
             <Image src="/images/IMG_4860.png" alt="NFT" width={200} height={200} />
            <p>Pro</p>
            <button onClick={(() => {
                checkout({
                  lineItems: [
                    {
                      price: "price_1LKJGDSJFDFywDTJdNnDZwCF",
                      quantity: 1
                    }
                  ]
                })
              })}>Buy @ $19
            </button>
          </div>
          
          <div className={styles.card}>
             <Image src="/images/IMG_4860.png" alt="NFT" width={200} height={200} />
            <p>Enterprise</p>
            <button onClick={(() => {
                checkout({
                  lineItems: [
                    {
                      price: "price_1LKJFNSJFDFywDTJsJeN1jw1",
                      quantity: 1
                    }
                  ]
                })
              })}>Buy @ $119
            </button>
          </div>

        </div>
      </main>

    </div>
  )
}
