import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { checkout } from '../checkout'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Buy my Physical NFTs
        </h1>

        <div className={styles.grid}>

          <div>
            <Image src="/images/medium.png" alt="NFT" width={400} height={400} />
            <p>Art Piece 1</p>
            <button onClick={(() => {
                checkout({
                  lineItems: [
                    {
                      price: "price_1LKJFNSJFDFywDTJsJeN1jw1",
                      quantity: 1
                    }
                  ]
                })
              })}>Buy!
            </button>
          </div>
            
          <div>
             <Image src="/images/IMG_4860.png" alt="NFT" width={400} height={400} />
            <p>Art Piece 2</p>
            <button>Buy!</button>
          </div>
          
        </div>
      </main>

    </div>
  )
}
